version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.21.6
    container_name: front-envoy
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8080:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster front-proxy --log-format '[SYSTEM][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_a_envoy:
    image: envoyproxy/envoy-alpine:v1.21.6
    container_name: service-a-envoy
    volumes:
      - ./service_a/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8786:8786"
      - "8788:8788"
      - "8791:8791"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster service-a --log-format '[SYSTEM][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_a:
    build: service_a/
    container_name: service-a
    ports:
      - "8081:8081"

  service_b_envoy:
    image: envoyproxy/envoy-alpine:v1.21.6
    container_name: service-b-envoy
    volumes:
      - ./service_b/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8789:8789"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster service-b --log-format '[SYSTEM][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_b:
    build: service_b/
    container_name: service-b
    ports:
      - "8082:8082"

  service_c_envoy:
    image: envoyproxy/envoy-alpine:v1.21.6
    container_name: service-c-envoy
    volumes:
      - ./service_c/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8790:8790"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster service-c --log-format '[SYSTEM][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_c:
    build: service_c/
    container_name: service-c
    ports:
      - "8083:8083"

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686"